### ISSUE TITLE
Design the Tasks Page

### ISSUE THREAD

**Issue by TzivyaFireman** [TzivyaFireman/tasksListProject#1]
Redesign the tasks page to make it more user-friendly and visually appealing.
Consider adding better task organization, improved spacing, and a modern color scheme.

**Comment by Min1600** [comment]
Hi I would like to contribute.

**Comment by TzivyaFireman** [comment]
Thank you for your interest in the project!
Assigned to you.
I just want to clarify that this is a small and not particularly significant project, but it could be a wonderful opportunity to dive into open source.
Of course, it’s completely fine if you decide it’s not the right fit for you!
Feel free to reach out if you have any questions or want to discuss the project further.

**Comment by TzivyaFireman** [comment]
Hey @Min1600 ,
Could you please take a look at the #3 PR? It would be great if you could adjust the design of this page to be more in line with the style of the other one.
 Thanks in advance!

**Comment by Min1600** [comment]
> Thank you for your interest in the project! Assigned to you. I just want to clarify that this is a small and not particularly significant project, but it could be a wonderful opportunity to dive into open source. Of course, it’s completely fine if you decide it’s not the right fit for you! Feel free to reach out if you have any questions or want to discuss the project further.

Hi, I cannot seem to access the tasks.html or users.html webpage and the dotnet run only launches the login page of index.html. I get error saying "file cannot be found"

**Comment by Min1600** [comment]
![Screenshot (47)](https://github.com/user-attachments/assets/7207c654-4e72-4c78-8bdb-b0b4f0c3c649)
![Screenshot (48)](https://github.com/user-attachments/assets/05a32b4b-a8cb-4cb1-b30b-cad1e219f600)
![Screenshot (51)](https://github.com/user-attachments/assets/9b61d0bc-40c9-4309-9bd2-53c470fcf401)
![Screenshot (52)](https://github.com/user-attachments/assets/220118b1-778a-4638-b82d-cd2a0f131bb7)


Hi, as requested I tried to follow the design of the previous page. When you press the edit button the screen changes as shown in my second screenshot. 

I have made it so the edit and delete button only appear when hovering please let me know if you would like those buttons to be on screen at all times instead. I added the username on the top and removed the CRUD header, let me know if you would like any changes there. 

I have provided some different colour templates as well. Please let me know if you would like to change anything. Thank you.
