### ISSUE TITLE
Design the Login Page

### ISSUE THREAD

**Issue by TzivyaFireman** [TzivyaFireman/tasksListProject#3]
Update the login page with a modern, clean design.

**Comment by OMIIIEE** [comment]
please assign me

**Comment by TzivyaFireman** [comment]
Thank you for your interest in the project!
Please note that this is a small and not particularly significant project,
 but it could be a great opportunity to get into open source.
No worries if you decide it’s not for you – that’s completely fine! 
If you need, I’m here for questions and discussions.

**Comment by TzivyaFireman** [comment]
Thank you for designing the page and paying attention to the small details,
it truly makes a difference!
